# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    name: CI with Maven

    runs-on: ubuntu-latest
    env:
      working-directory: ./hello

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2 # Github action이 실행될 때 OS에 자바설치
      
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: ./hello
